# Localization file (english).
TEXT = 'Enter the text: '
VOWELS = 'aeiou'
SENTENCES = 'Suggestions: '
WORD = 'Words: '
SYLLABLES = 'Syllables: '
AVERAGE_SENTENCES = 'Average sentence length in words: '
AVERAGE_WORD = 'Average syllable length: '
INDEX_FLESH = 'Flush readability index: '
TEXT_EASY = 'The text is very easy to read (for younger students).'
TEXT_SIMPLE = 'Simple text (for students).'
TEXT_LITTLE_HARD = 'The text is a little hard to read (for students).'
TEXT_DIFFICULT = 'The text is hard to read (for graduates).'
